<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mdp_bringup</name>
  <version>0.0.1</version>
  <description>Top-level launch files to bring up the mdp_car robot</description>
  <maintainer email="alvinwm0523@gmail.com">wm_u26</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>mdp_description</exec_depend>
  <exec_depend>mdp_hardware_bridge</exec_depend>
  <exec_depend>mdp_vision</exec_depend>
  <exec_depend>robot_localization</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
