#!/usr/bin/env python3
"""
Reeds-Shepp shortest-path length between two (x, y, theta) poses, for a
vehicle that can move forward and reverse. Used as an admissible heuristic
by hybrid_astar.py and as an optional distance metric by hamiltonian.py.

Ported from the teammate's mdp_algo package (pathfinding/reeds_shepp.py) -
the 12 path-family formulas (Reeds & Shepp 1990) are copied as-is, only the
imports and the deg/rad bug (see geometry_utils.py's module docstring) are
fixed. Named reeds_shepp_curves.py (not reeds_shepp_planner.py) to avoid
colliding with the existing Dubins-only planner of that name in this
package - that one has no reverse-gear/collision awareness, this one does.
"""

import math
from dataclasses import dataclass, replace
from typing import List, Tuple

from .geometry_utils import M, R, change_of_basis
from .motion_primitives import Gear, Steering

Pose = Tuple[float, float, float]


@dataclass(eq=True)
class PathElement:
    param: float
    steering: Steering
    gear: Gear

    @classmethod
    def create(cls, param: float, steering: Steering, gear: Gear):
        if param >= 0:
            return cls(param, steering, gear)
        return cls(-param, steering, gear).reverse_gear()

    def __repr__(self):
        return (f"{{ Steering: {self.steering.name}\tGear: {self.gear.name}"
                f"\tdistance: {round(self.param, 2)} }}")

    def reverse_steering(self):
        return replace(self, steering=Steering(-self.steering.value))

    def reverse_gear(self):
        return replace(self, gear=Gear(-self.gear.value))


def path_length(path: List[PathElement]) -> float:
    return sum(e.param for e in path)


def get_optimal_path(start: Pose, end: Pose) -> List[PathElement]:
    """Shortest path (in unit-turning-radius units) among all valid families."""
    paths = get_all_paths(start, end)
    if not paths:
        # start ~= end (or another degenerate case none of the 48 path
        # variants covers) - zero-length path is the correct answer, not
        # an error.
        return []
    return min(paths, key=path_length)


def get_optimal_path_length(start: Pose, end: Pose, radius: float) -> float:
    """Shortest Reeds-Shepp path length in the same linear units as
    start/end and radius (this package uses centimetres throughout, see
    occupancy_map.py's module docstring)."""
    x_0, y_0 = start[0] / radius, start[1] / radius
    x_f, y_f = end[0] / radius, end[1] / radius
    opt_path = get_optimal_path((x_0, y_0, start[2]), (x_f, y_f, end[2]))
    return radius * path_length(opt_path)


def get_all_paths(start: Pose, end: Pose) -> List[List[PathElement]]:
    """All paths from start to end generated by the 12 path families and
    their 4 symmetry variants (timeflip/reflect) each."""
    path_fns = [path1, path2, path3, path4, path5, path6,
                path7, path8, path9, path10, path11, path12]
    paths = []

    x, y, theta = change_of_basis(start, end)

    def _safe(get_path, px, py, ptheta):
        # Several path formulas divide by a `rho` that can be exactly (or
        # via float error, near-) zero for very short/degenerate start->end
        # geometry (e.g. start almost equal to end), and some take
        # acos/asin of an expression that can drift fractionally outside
        # [-1, 1] at these extremes - both raise here rather than returning
        # a family that simply doesn't apply. Treat either the same as the
        # `if rho <= 4:`-style guards already in each formula: this family
        # doesn't produce a valid path for this (x, y, theta), skip it -
        # other families still cover the heuristic.
        try:
            return get_path(px, py, ptheta)
        except (ZeroDivisionError, ValueError):
            return []

    for get_path in path_fns:
        paths.append(_safe(get_path, x, y, theta))
        paths.append(timeflip(_safe(get_path, -x, y, -theta)))
        paths.append(reflect(_safe(get_path, x, -y, -theta)))
        paths.append(reflect(timeflip(_safe(get_path, -x, -y, theta))))

    for i in range(len(paths)):
        paths[i] = [e for e in paths[i] if e.param != 0]

    return [p for p in paths if p]


def timeflip(path: List[PathElement]) -> List[PathElement]:
    return [e.reverse_gear() for e in path]


def reflect(path: List[PathElement]) -> List[PathElement]:
    return [e.reverse_steering() for e in path]


def path1(x, y, phi):
    """Formula 8.1: CSC (same turns)."""
    path = []
    u, t = R(x - math.sin(phi), y - 1 + math.cos(phi))
    v = M(phi - t)
    path.append(PathElement.create(t, Steering.LEFT, Gear.FORWARD))
    path.append(PathElement.create(u, Steering.STRAIGHT, Gear.FORWARD))
    path.append(PathElement.create(v, Steering.LEFT, Gear.FORWARD))
    return path


def path2(x, y, phi):
    """Formula 8.2: CSC (opposite turns)."""
    phi = M(phi)
    path = []
    rho, t1 = R(x + math.sin(phi), y - 1 - math.cos(phi))
    if rho * rho >= 4:
        u = math.sqrt(rho * rho - 4)
        t = M(t1 + math.atan2(2, u))
        v = M(t - phi)
        path.append(PathElement.create(t, Steering.LEFT, Gear.FORWARD))
        path.append(PathElement.create(u, Steering.STRAIGHT, Gear.FORWARD))
        path.append(PathElement.create(v, Steering.RIGHT, Gear.FORWARD))
    return path


def path3(x, y, phi):
    """Formula 8.3: C|C|C."""
    path = []
    xi = x - math.sin(phi)
    eta = y - 1 + math.cos(phi)
    rho, theta = R(xi, eta)
    if rho <= 4:
        A = math.acos(rho / 4)
        t = M(theta + math.pi / 2 + A)
        u = M(math.pi - 2 * A)
        v = M(phi - t - u)
        path.append(PathElement.create(t, Steering.LEFT, Gear.FORWARD))
        path.append(PathElement.create(u, Steering.RIGHT, Gear.REVERSE))
        path.append(PathElement.create(v, Steering.LEFT, Gear.FORWARD))
    return path


def path4(x, y, phi):
    """Formula 8.4 (1): C|CC."""
    path = []
    xi = x - math.sin(phi)
    eta = y - 1 + math.cos(phi)
    rho, theta = R(xi, eta)
    if rho <= 4:
        A = math.acos(rho / 4)
        t = M(theta + math.pi / 2 + A)
        u = M(math.pi - 2 * A)
        v = M(t + u - phi)
        path.append(PathElement.create(t, Steering.LEFT, Gear.FORWARD))
        path.append(PathElement.create(u, Steering.RIGHT, Gear.REVERSE))
        path.append(PathElement.create(v, Steering.LEFT, Gear.REVERSE))
    return path


def path5(x, y, phi):
    """Formula 8.4 (2): CC|C."""
    path = []
    xi = x - math.sin(phi)
    eta = y - 1 + math.cos(phi)
    rho, theta = R(xi, eta)
    if rho <= 4:
        u = math.acos(1 - rho * rho / 8)
        A = math.asin(2 * math.sin(u) / rho)
        t = M(theta + math.pi / 2 - A)
        v = M(t - u - phi)
        path.append(PathElement.create(t, Steering.LEFT, Gear.FORWARD))
        path.append(PathElement.create(u, Steering.RIGHT, Gear.FORWARD))
        path.append(PathElement.create(v, Steering.LEFT, Gear.REVERSE))
    return path


def path6(x, y, phi):
    """Formula 8.7: CCu|CuC."""
    path = []
    xi = x + math.sin(phi)
    eta = y - 1 - math.cos(phi)
    rho, theta = R(xi, eta)
    if rho <= 4:
        if rho <= 2:
            A = math.acos((rho + 2) / 4)
            t = M(theta + math.pi / 2 + A)
            u = M(A)
            v = M(phi - t + 2 * u)
        else:
            A = math.acos((rho - 2) / 4)
            t = M(theta + math.pi / 2 - A)
            u = M(math.pi - A)
            v = M(phi - t + 2 * u)
        path.append(PathElement.create(t, Steering.LEFT, Gear.FORWARD))
        path.append(PathElement.create(u, Steering.RIGHT, Gear.FORWARD))
        path.append(PathElement.create(u, Steering.LEFT, Gear.REVERSE))
        path.append(PathElement.create(v, Steering.RIGHT, Gear.REVERSE))
    return path


def path7(x, y, phi):
    """Formula 8.8: C|CuCu|C."""
    path = []
    xi = x + math.sin(phi)
    eta = y - 1 - math.cos(phi)
    rho, theta = R(xi, eta)
    u1 = (20 - rho * rho) / 16
    if rho <= 6 and 0 <= u1 <= 1:
        u = math.acos(u1)
        A = math.asin(2 * math.sin(u) / rho)
        t = M(theta + math.pi / 2 + A)
        v = M(t - phi)
        path.append(PathElement.create(t, Steering.LEFT, Gear.FORWARD))
        path.append(PathElement.create(u, Steering.RIGHT, Gear.REVERSE))
        path.append(PathElement.create(u, Steering.LEFT, Gear.REVERSE))
        path.append(PathElement.create(v, Steering.RIGHT, Gear.FORWARD))
    return path


def path8(x, y, phi):
    """Formula 8.9 (1): C|C[pi/2]SC."""
    path = []
    xi = x - math.sin(phi)
    eta = y - 1 + math.cos(phi)
    rho, theta = R(xi, eta)
    if rho >= 2:
        u = math.sqrt(rho * rho - 4) - 2
        A = math.atan2(2, u + 2)
        t = M(theta + math.pi / 2 + A)
        v = M(t - phi + math.pi / 2)
        path.append(PathElement.create(t, Steering.LEFT, Gear.FORWARD))
        path.append(PathElement.create(math.pi / 2, Steering.RIGHT, Gear.REVERSE))
        path.append(PathElement.create(u, Steering.STRAIGHT, Gear.REVERSE))
        path.append(PathElement.create(v, Steering.LEFT, Gear.REVERSE))
    return path


def path9(x, y, phi):
    """Formula 8.9 (2): CSC[pi/2]|C."""
    path = []
    xi = x - math.sin(phi)
    eta = y - 1 + math.cos(phi)
    rho, theta = R(xi, eta)
    if rho >= 2:
        u = math.sqrt(rho * rho - 4) - 2
        A = math.atan2(u + 2, 2)
        t = M(theta + math.pi / 2 - A)
        v = M(t - phi - math.pi / 2)
        path.append(PathElement.create(t, Steering.LEFT, Gear.FORWARD))
        path.append(PathElement.create(u, Steering.STRAIGHT, Gear.FORWARD))
        path.append(PathElement.create(math.pi / 2, Steering.RIGHT, Gear.FORWARD))
        path.append(PathElement.create(v, Steering.LEFT, Gear.REVERSE))
    return path


def path10(x, y, phi):
    """Formula 8.10 (1): C|C[pi/2]SC."""
    path = []
    xi = x + math.sin(phi)
    eta = y - 1 - math.cos(phi)
    rho, theta = R(xi, eta)
    if rho >= 2:
        t = M(theta + math.pi / 2)
        u = rho - 2
        v = M(phi - t - math.pi / 2)
        path.append(PathElement.create(t, Steering.LEFT, Gear.FORWARD))
        path.append(PathElement.create(math.pi / 2, Steering.RIGHT, Gear.REVERSE))
        path.append(PathElement.create(u, Steering.STRAIGHT, Gear.REVERSE))
        path.append(PathElement.create(v, Steering.RIGHT, Gear.REVERSE))
    return path


def path11(x, y, phi):
    """Formula 8.10 (2): CSC[pi/2]|C."""
    path = []
    xi = x + math.sin(phi)
    eta = y - 1 - math.cos(phi)
    rho, theta = R(xi, eta)
    if rho >= 2:
        t = M(theta)
        u = rho - 2
        v = M(phi - t - math.pi / 2)
        path.append(PathElement.create(t, Steering.LEFT, Gear.FORWARD))
        path.append(PathElement.create(u, Steering.STRAIGHT, Gear.FORWARD))
        path.append(PathElement.create(math.pi / 2, Steering.LEFT, Gear.FORWARD))
        path.append(PathElement.create(v, Steering.RIGHT, Gear.REVERSE))
    return path


def path12(x, y, phi):
    """Formula 8.11: C|C[pi/2]SC[pi/2]|C."""
    path = []
    xi = x + math.sin(phi)
    eta = y - 1 - math.cos(phi)
    rho, theta = R(xi, eta)
    if rho >= 4:
        u = math.sqrt(rho * rho - 4) - 4
        A = math.atan2(2, u + 4)
        t = M(theta + math.pi / 2 + A)
        v = M(t - phi)
        path.append(PathElement.create(t, Steering.LEFT, Gear.FORWARD))
        path.append(PathElement.create(math.pi / 2, Steering.RIGHT, Gear.REVERSE))
        path.append(PathElement.create(u, Steering.STRAIGHT, Gear.REVERSE))
        path.append(PathElement.create(math.pi / 2, Steering.LEFT, Gear.REVERSE))
        path.append(PathElement.create(v, Steering.RIGHT, Gear.FORWARD))
    return path
