GRID_SIZE = 40

# Physical dimensions (centimetres). Keep the task specification in one place.
ARENA_SIZE_CM = 200
START_ZONE_SIZE_CM = 40
OBSTACLE_SIZE_CM = 10
ROBOT_WIDTH_CM = 20
ROBOT_LENGTH_CM = 21
PLANNING_FOOTPRINT_CM = 30
VIRTUAL_OBSTACLE_SIZE_CM = OBSTACLE_SIZE_CM + PLANNING_FOOTPRINT_CM
IMAGE_DISTANCE_CM = 20

# simulation parameters
WIDTH = 1200
HEIGHT = 900

MAP_WIDTH = 800
MAP_HEIGHT = 800
MAP_X0 = 50
MAP_Y0 = 50

BORDER_THICKNESS = 5

TURNING_RADIUS = 26.75
REAR_AXLE_TO_CENTER = 9.5
